apiVersion: v2
name: microservices-app
description: A Helm chart for microservices application tutorial
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - kubernetes
  - tutorial
  - nodejs
  - python
home: https://github.com/example/k8s-tutorial
sources:
  - https://github.com/example/k8s-tutorial
maintainers:
  - name: Tutorial Author
    email: author@example.com
