version: '3.8'

services:
  # Frontend Service
  frontend:
    build: ../sample-app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - API_GATEWAY_URL=http://api-gateway:8080

  # API Gateway
  api-gateway:
    build: ../sample-app/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:5000

  # User Service
  user-service:
    build: ../sample-app/user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/users
      - REDIS_URL=redis://redis:6379

  # Product Service
  product-service:
    build: ../sample-app/product-service
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379

  # MongoDB for User Service
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=users

  # PostgreSQL for Product Service
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Redis for Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
